"""agregar imagen_url a categorias

Revision ID: 84e304e6c0cd
Revises: b1dcf0e10c99
Create Date: 2026-08-30 15:13:11.408006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e304e6c0cd'
down_revision: Union[str, None] = 'b1dcf0e10c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'imagen_url')
    # ### end Alembic commands ###
