"""replace has_admin with roles array

Revision ID: a1fce333b110
Revises: 84e304e6c0cd
Create Date: 2026-09-26 19:15:29.660645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fce333b110'
down_revision: Union[str, None] = '84e304e6c0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('roles', sa.ARRAY(sa.String()), 
                                        nullable=False,
                                        server_default='{viewer}'
                                        ))

    op.execute("""
        UPDATE usuarios
        SET roles = CASE
            WHEN has_admin THEN ARRAY['admin']
            ELSE ARRAY['viewer']
        END
    """)
    
    op.drop_column('usuarios', 'has_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('has_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'roles')
    # ### end Alembic commands ###
